<!DOCTYPE html>
<html class="no-js" lang="">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Thofik Wiranata Blog | Front-end Engineer Indonesia</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!-- Place favicon.ico in the root directory -->

    <link rel="stylesheet" type='text/css' href="/css/app.css" />
  </head>
  <body id="body">
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

    <!-- Add your site or application content here -->

    <div class="wrapper" id="app">
      <header-component></header-component>
      <div class="content container-910">
        <router-view></router-view>
      </div>
      <footer-component></footer-component>
    </div>
    
    <script type="text/x-template" id="pagination">
      <ul class="pagination">
        <li class="pagination__li active" v-for="i in 3" v-if="i === 1"><a href="#" class="pagination__a">{{ i }}</a></li>
        <li class="pagination__li" v-else><a href="#" class="pagination__a">{{ i }}</a></li>
        <li class="pagination__li"><a href="#" class="pagination__a"><i class="fa fa-angle-right"></i></a></li>
      </ul>
    </script>
    <script type="text/x-template" id="homeComponent">
      <div>
        <div class="post-classic" v-for="news in latestNews">
          <div class="post-classic__thumbnail img-cover mb_28" v-bind:style="{backgroundImage: 'url(' + '/images/article/' + news.img_desktop + ')' }" ></div>

          <div class="post-classic__content">
            <h2 class="post-classic__title"><a :href="'/detail/' + news.id" rel="bookmark">{{ news.title }}</a></h2>
            
            <div class="post-classic__toolbar mb_14 xs-mb_10">
              <span><i class="fa fa-tag"></i>Tags<a href="#">{{ news.tag }}</a></span>
              <span>{{ dateToMdY(news.publish_date) }}</span>
              <span><a href="#">Leave a comment</a></span>
            </div>

            <p>{{ news.teaser }}..</p>
            
            <div class="post-classic__group">
              <!-- <router-link :to="{ path: 'detail', params: { id: news.id }}" class="btn-read-more btn btn_round">Continue Reading</router-link> -->
              <a :href="'/detail/' + news.id" class="btn-read-more btn btn_round">Continue Reading</a>
            </div>
          </div>
        </div>
        <pagination></pagination>
      </div>
    </script>
    <script type="text/x-template" id="headerComponent">
      <div>
        <header class="header lora mb_42 hidden-mobile">
          <div class="container-910">
            <div class="row">
              <div class="large7 column">
                <list-menu></list-menu>
              </div>

              <div class="large5 column text-right">
                <form class="form-search-header">
                  <input type="search" name="search_article" class="search-header" placeholder="Hit enter to search">
                </form>
              </div>
            </div>
          </div>
        </header>
        
        <div class="ct-header-mobile">
          <header class="header mb_30 hidden-desktop">
            <div class="mobile-menu" v-on:click="slideToggle(menuMobileActive)">
              <span class="mobile-menu__text">Menu</span>
              <span class="mobile-menu__strip">-</span>
              <span class="mobile-menu__strip">-</span>
              <span class="mobile-menu__strip">-</span>
            </div>
            <transition 
              name="custom-classes-transition"
              enter-active-class="animated fadeIn"
              leave-active-class="animated fadeOut" :duration="150">
              <div class="mobile-menu-list" v-if="menuMobileActive">
                <list-menu class="list-menu--mobile" v-on:slidetoggle="slideToggle" v-bind:state="menuMobileActive"></list-menu>
                <div class="mobile-menu-list__search">
                  <input type="text" class="mobile-menu-list__input" placeholder="Hit enter to search">
                </div>
              </div>
            </transition>
          </header>
        </div>
      </div>
    </script>
    <script type="text/x-template" id="listMenu">
     <ul class="list-menu">
       <li class="list-menu__li" v-for="menu in menus"><a :href="menu.path" class="list-menu__li__a" v-on:click="tickToggle(state)">{{ menu.text }}</a></li>
     </ul> 
    </script>
    <script type="text/x-template" id="listArticle">
      <div>
        <h3 class="list-article-heading lora-bold">{{ heading }}</h3>
        <ul class="list-article">
          <li class="list-article__item" v-for="i in 5">
            <div class="list-article__content">
              <a href="#" class="list-article__title lora-bold">Amazing Classic Interior Design With Perfect Lighting</a>
              <span class="list-article__datetime">May 17, 2015</span>
            </div>
          </li>
        </ul>
      </div>
    </script>
    <script type="text/x-template" id="footerComponent">
      <footer class="ct-footer">
        <div class="snapwidget-container">
          <div class="hidden-mobile">
            <iframe src="https://snapwidget.com/embed/361202" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:100%;display: block;"></iframe>
          </div>
          <div class="hidden-desktop">
            <iframe src="https://snapwidget.com/embed/486777" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:100%;display: block; "></iframe>
          </div>
        </div>
        <div class="footer">
          <div class="footer-content container-910">
            <div class="row">
              <div class="column large4 medium4 small4 mobile12">
                <h3 class="list-article-heading">About Me</h3>
                <img class="img-responsive mb_18 img-round" src="/images/avatar.jpg" alt="About Me">
                <p class="mb_18 size_14 lh_20 xs-mb_4">Hello World, I am Front-end Engineer in <a href="http://qeon.com/" target="_blank" class="link-underline">Qeon Interactive</a> and also freelancer.</p>

                <p class=" size_14 lh_20 mb_18 xs-mb_20">If you have a cool projects in mind, Don't hesitate. Contact me on phone +6281287299922.</p>
              </div>

              <div class="column large4 medium4 small4 mobile12">
                
                <list-article heading="Popular Posts"></list-article>
                
              </div>

              <div class="column large4 medium4 small4 mobile12">
                <list-article heading="List Free e'books"></list-article>
              </div>
            </div>
          </div>
          <div class="container-910 pt_16 pb_16">
            <p class="footer-copyright size_12">© 2017 Thofik Wiranata, INC. All Rights Reserved.</p>
          </div>
        </div>
      </footer>
    </script>
    <script type="text/x-template" id="detailComponent">
      <div>

        <img src="/images/Resturant-Employer-940x400.jpg" class="img-responsive img-round mb_28">

        <div class="container-710">
          <div class="detail-content">
            <h1 class="title-article lora-bold size_24 mb_8">{{ article.title }}</h1>

            <div class="post-classic__toolbar mb_14">
              <span><i class="fa fa-tag"></i>Tags<a href="#">{{ article.tag }}</a></span>
              <span>{{ dateToMdY(article.publish_date) }}</span>
            </div>
            
            <div v-html="article.content"></div>

            <ul class="list-share">
              <li class="list-share__icon list-share__icon--default">
                <a href="#" class="list-share__link"><i class="fa fa-share"></i></a>
              </li>
              <li class="list-share__icon link-share__icon--fb">
                <a href="#" class="list-share__link"><i class="fa fa-facebook"></i></a>
              </li>
              <li class="list-share__icon link-share__icon--twitter">
                <a href="#" class="list-share__link "><i class="fa fa-twitter"></i></a>
              </li>
              <li class="list-share__icon link-share__icon--linkedin">
                <a href="#" class="list-share__link"><i class="fa fa-linkedin"></i></a>
              </li>
            </ul>
          </div>
        </div>

        <div class="detail-others">
          <div class="post-navigation">
            <div class="row row0">
              <div class="column column_gutter25 large6 medium6 small6 mobile12">
                <a href="#" class="post-navigation__link post-navigation__link--prev">
                  <div class="post-navigation__thumbnail to-left">
                    <div class="img-cover post-navigation__thumbnail" style="background-image: url('/images/Desserts-150x150.jpg')"></div>
                  </div>
                  <div class="post-navigation__content pl_80">
                    <span class="post-navigation__h block">Previous Post:</span>
                    <span class="post-navigation__title block lora-bold">English Breakfast Tea With Tasty Donut Desserts</span>
                  </div>
                </a>
              </div>

              <div class="column column_gutter25 large6 medium6 small6 mobile12">
                <a href="#" class="post-navigation__link post-navigation__link--next">
                  <div class="post-navigation__thumbnail to-right">
                    <div class="img-cover post-navigation__thumbnail" style="background-image: url('/images/Desserts-150x150.jpg')"></div>
                  </div>
                  <div class="post-navigation__content pr_80 text-right">
                    <span class="post-navigation__h block">Next Post:</span>
                    <span class="post-navigation__title block lora-bold">English Breakfast Tea With Tasty Donut Desserts</span>
                  </div>
                </a>
              </div>
            </div>
          </div>

          <div class="related-post">
            <h2 class="related-post__h mb_20">Related Post:</h2>
            <div class="row">
              <div class="column large4 medium4 small4 mobile12">
                <div class="related-post__item">
                  <img src="/images/Talking-Coworkers-455x310.jpg" class="related-post__img img-responsive img-round">

                  <a href="#" class="related-post__title lora-bold">Co-founder Trying To Explain His Idea To His Employers</a>
                </div>
              </div>

              <div class="column large4 medium4 small4 mobile12">
                <div class="related-post__item">
                  <img src="/images/Smart-Girl-455x310.jpg" class="related-post__img img-responsive img-round">
                  <a href="#" class="related-post__title lora-bold">Girl With Beautiful Eyes Wants To Fly</a>
                </div>
              </div>

              <div class="column large4 medium4 small4 mobile12">
                <div class="related-post__item">
                  <img src="/images/Blue-Sea-Water-455x310.jpg" class="related-post__img img-responsive img-round">
                  <a href="#" class="related-post__title lora-bold">Modern City With Amazing Dark Blue Sea</a>
                </div>
              </div>
            </div>
          </div>

          <div class="ct-comment">
            <h2 class="comment-h size_17 mb_15">Leave a reply: </h2>
            <p class="comment-notes">Your email address will not be published.</p>

            <form>
              <div class="row">
                <div class="column large12 medium12 small12 mobile12">
                  <textarea class="form-control" style="height: 171px"></textarea>
                </div>
              </div>

              <div class="row">
                <div class="column large4 medium4 small4 mobile12">
                  <input type="text" class="form-control" placeholder="Name">
                </div>

                <div class="column large4 medium4 small4 mobile12">
                  <input type="text" class="form-control" placeholder="Email">
                </div>

                <div class="column large4 medium4 small4 mobile12">
                  <input type="text" class="form-control" placeholder="Website">
                </div>
              </div>

              <div class="text-left mt_16">
                <input name="submit" type="submit" id="submit" class="btn btn_round btn-post-comment lora-bold" value="Post Comment">
              </div>
            </form>
          </div>
        </div>
      </div>
    </script>
    
    <script src="/vendor/snapwidget/snapwidget.js"></script>
    <script src="/vendor/vue/vue.js"></script>
    <script src="/vendor/vue/vue-router.js"></script>
    <script src="/vendor/vue/vue-resource.min.js"></script>
    <script src="/js/app.js"></script>
  </body>
</html>
